version: '3.1'
services:
  main-server:
    build: ./main-service
    image: ewm-main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SERVER_PORT=8080
      - STATS-SERVER-URL=http://stats-server:9090
      - DATASOURCE_URL=jdbc:postgresql://db:5433/explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  main-db:
    image: postgres:14-alpine
    container_name: ewm-main-database
    ports:
      - "6542:5433"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-server:
    build: ./stats/stats-server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SERVER_PORT=9090
      - DATASOURCE_URL=jdbc:postgresql://db:5432/explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-database
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore-with-me
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test